#+title: GUST

This project's main repository is on [[https://codeberg.org/Kyuvi/gust][Codeberg.org]], if you are viewing this anywhere else, it is just a mirror, please use the [[https://codeberg.org/Kyuvi/gust][Codeberg.org]] repository for pull requests and issues, Thank you.

* Description

A set of Guile Scheme modules to increase speed and efficiency when writing code.

* Motivation

[[https://www.gnu.org/software/guile/][Guile]] is a powerful [[https://en.wikipedia.org/wiki/Scheme_(programming_language)][Scheme]] variant that is very well integrated with the GNU/Linux ecosystem. That said Scheme, to my understanding, was designed in the 70's to prove a set of particular (academic) points and understand certain aspects of programming, which is did very well as can be seen from the persistence and the adoption of many of its ideas in other places.

I use Guile mainly for Linux based programming, in most other settings, I use [[https://clojure.org/][Clojure]] or [[https://clojurescript.org/][a]] [[https://github.com/Tensegritics/ClojureDart][variant]], which in my view has a more practical design for getting things done quickly. Gust is an attempt to bring that practical design philosophy to Guile (cf. Paul Graham's [[https://www.paulgraham.com/popular.html][Being popular]] and [[https://www.paulgraham.com/langdes.html][5 questions about language design]]) in a simple way, and ease my switching back and forth, without compromising on Guile's positive attributes.

This is not a Clojure clone nor is it trying to be, for something closer to that on Guile, see [[https://github.com/lokke-org/lokke][Lokke]].

* Usage

+ Download/Clone the repo and place the folder(s) contained in './src' either to the somewhere on Guile's '%load-path' or extend the '%load-path' (using the environment variable 'GUILE_LOAD_PATH') to include folder(s).
+ add ~(use-modules (gust gust) (gust repl))~ to your ~/.guile file. (gust gust) exports procedures from core.scm, io.scm, math.scm, coll.scm, obj.scm and os/gos.scm.
+ add (gust gust) (or other modules) to your production code to use it there as well
+ (gust os cmd) - OS command helpers and  (gust os files) - OS file helpers, as needed.

* Goals and Plans

** Goals
+ Fast startup - Keep Guile's near instant start up
+ Full Guile compatibility
+ Ease of installation - the main functions can be imported from (gust gust) or from the individual modules as needed. It should always be just a folder (or two) of scheme code to add to Guile's '%load-path' without needing any complex procedures.
+ Simplicity
+ Intuitive
+ Brevity

** Non-goals
+ Clojure compatibility

** TODO
+ defc - define + case-lambda(+ *) (similar to defn in Clojure)
+ letv - a sequential destructuring let (i.e let* with destructuring built in, similar to that of Clojure)
+ Language on Guile - This is a goal as long as it is possible to still use modules written in Guile from Gust and vice versa and it remains "just a couple of folders" on the '%load-path'.
+ ns - an improved Clojure like modules system (swapping :require with :use and mapped unto the underlying define-module system, maybe adding module documentation) for the language above .
+ "Namespace isolated"/"qualified symbols" macro definition facility (similar to Clojure's)

Pull requests are welcome.

* Donations

If you would like to support my work, please donate. (with a message containing the project name you would like to support)

** Monero
42s4DCgjk2sguR8x1H4Svx7sBuysvrRHGCK3pfQTcEerNBUGhT43gMy6noctiGeVeo61aFzsQfGwVTxNmruy3dqb8PAyYZM

** Bitcoin
bc1quymsg5tvyvqkcn35zzujfdrdwgxnakqaptqc5k

** LiteCoin
ltc1q8ese8e8rl9c80emqgvek24gylz32u3d76v2e9q

** Paypal
Please use, <My username> at gmx dot com

* License
Copyright © 2025 Kyuvi

This program is published under version 3 of the GNU General Public license.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
